services:
  mimicwx:
    build: .
    container_name: mimicwx-linux
    stdin_open: true # docker attach 需要 (-i)
    tty: true # 终端模式 (-t)
    cap_add:
      - SYS_ADMIN # fanotify WAL 监听
      - SYS_PTRACE # GDB 密钥提取
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "5901:5901" # VNC
      - "6080:6080" # noVNC
      - "8899:8899" # MimicWX API
    volumes:
      - wechat-data:/home/wechat/.xwechat
      - .:/home/wechat/mimicwx-linux
    shm_size: '512m'
    tmpfs:
      - /tmp
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-sf", "http://localhost:8899/status" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s

volumes:
  wechat-data:
